= SAE 3.01 DevApp 2024-2025

Projet est réalisé par::

- https://github.com/aminaAbv[ABAYEV Amina] : Product Owner
- https://github.com/alexian-a[ARGUELLES Alexian] : Scrum Master
- https://github.com/gadbinhugo[GADBIN Hugo] : Développeur
- https://github.com/Bob-the-great-the-third[DELAPLAGNE Titouan] : Développeur

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]

// Vous y trouverez des fichiers qui peuvent être supprimés s'ils ne vous sont pas utiles :

// - `.gitignore` => un fichier minimaliste des éléments à ne pas pousser en général sur vos dépôts (utiliser la commande // `git add -f` pour forcer l'ajout d'un fichier Jar qui ne bougera plus, pour archive par exemple).
// - `.github` => le répertoire qui contient des éléments de gestion de projet :
// ** `workflows` => le repertoire qui contient les actions à lancer à chaque push sur votre repo. 
// *** `blank.yml` => un exemple bidon mais dont vous pourrez vérifier l’exécution correcte (1er tag)
// ** `ISSUE_TEMPLATE` => le repertoire qui contient quelques templates pour vos issues.
// *** `us.yml` => Exemple de template pour les User Stories
// *** `bug.yml` => Exemple de template pour les issues de bug report

== Context du projet
...

== Backlog Produit : La Roue Tourne
...

== Documentation
- https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g1b4/blob/master/.github/GPO/Doc%20Conception.adoc[Document de conception]

== Réalisations
...

== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application

=== Evaluation bi-hebdomadaire des sprints  

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=1097914647&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=1097914647&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=1097914647&amp;format=interactive"></iframe>
++++
endif::[]

==== initialisation du dépôt:
Il faut retravailler le readme et enlever les consignes. Je n'ai aucun lien actif dans le readme !! Pas de documentation (pas même la conception), pas de cahier de recettes, aucune doc initialisée ! J'ai les US qui doivent être eclatée en issues/taches dans le sprint. En scrum on ne prévoit que le sprint à venir ! Venir me voir pour des précisions ou demander au groupe 2. Pour l'instant c'est très insuffisant. Il manque les rôles dans l'équipe.

