-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 15:25:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `idCategorieMère` INT NULL,
  PRIMARY KEY (`idCategorie`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Categorie_Categorie1_idx` (`idCategorieMère` ASC) VISIBLE,
  CONSTRAINT `fk_Categorie_Categorie1`
    FOREIGN KEY (`idCategorieMère`)
    REFERENCES `mydb`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produit` (
  `idProduit` INT NOT NULL AUTO_INCREMENT,
  `Categorie_idCategorie` INT NOT NULL,
  `prix` DOUBLE NULL,
  `nom` VARCHAR(45) NULL,
  `Description` VARCHAR(256) NULL,
  PRIMARY KEY (`idProduit`),
  INDEX `fk_Produit_Categorie1_idx` (`Categorie_idCategorie` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_Categorie1`
    FOREIGN KEY (`Categorie_idCategorie`)
    REFERENCES `mydb`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Adresse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `codePostal` CHAR(5) NULL,
  `ville` VARCHAR(45) NULL,
  `adresse` VARCHAR(80) NULL,
  PRIMARY KEY (`idAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(32) NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `numTel` CHAR(10) NOT NULL,
  `genreC` CHAR(1) NULL,
  `dateNaissance` DATE NULL,
  `Adresse_idAdresse` INT NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_Client_Adresse1_idx` (`Adresse_idAdresse` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Adresse1`
    FOREIGN KEY (`Adresse_idAdresse`)
    REFERENCES `mydb`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`PointRelais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PointRelais` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PointRelais` (
  `idPointRelais` INT NOT NULL AUTO_INCREMENT,
  `nomRelais` VARCHAR(45) NULL,
  `adresseRelais` VARCHAR(45) NULL,
  `codePostalRelais` CHAR(5) NULL,
  `villeRelais` VARCHAR(45) NULL,
  PRIMARY KEY (`idPointRelais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `Client_username` VARCHAR(16) NOT NULL,
  `typeLivraison` VARCHAR(45) NULL,
  `Adresse_idAdresse` INT NOT NULL,
  `PointRelais_idPointRelais` INT NOT NULL,
  `typePaiement` VARCHAR(16) NULL,
  `statut` VARCHAR(45) NULL DEFAULT 'En Cours',
  PRIMARY KEY (`idCommande`),
  INDEX `fk_Commande_Client1_idx` (`Client_username` ASC) VISIBLE,
  INDEX `fk_Commande_Adresse1_idx` (`Adresse_idAdresse` ASC) VISIBLE,
  INDEX `fk_Commande_PointRelais1_idx` (`PointRelais_idPointRelais` ASC) VISIBLE,
  CONSTRAINT `fk_Commande_Client1`
    FOREIGN KEY (`Client_username`)
    REFERENCES `mydb`.`Client` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Adresse1`
    FOREIGN KEY (`Adresse_idAdresse`)
    REFERENCES `mydb`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_PointRelais1`
    FOREIGN KEY (`PointRelais_idPointRelais`)
    REFERENCES `mydb`.`PointRelais` (`idPointRelais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Couleur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Couleur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Couleur` (
  `idCouleur` INT NOT NULL AUTO_INCREMENT,
  `nomCouleur` VARCHAR(64) NULL,
  PRIMARY KEY (`idCouleur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Taille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Taille` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Taille` (
  `idTaille` INT NOT NULL AUTO_INCREMENT,
  `nomTaille` VARCHAR(45) NULL,
  PRIMARY KEY (`idTaille`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VariantArticle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VariantArticle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VariantArticle` (
  `Produit_idProduit` INT NOT NULL,
  `Couleur_idCouleur` INT NOT NULL,
  `Taille_idTaille` INT NOT NULL,
  `Stock` INT NULL,
  `SeuilMin` INT NULL,
  `SeuilMax` INT NULL,
  PRIMARY KEY (`Produit_idProduit`, `Couleur_idCouleur`, `Taille_idTaille`),
  INDEX `fk_Produit_has_Couleur_Couleur1_idx` (`Couleur_idCouleur` ASC) VISIBLE,
  INDEX `fk_Produit_has_Couleur_Produit1_idx` (`Produit_idProduit` ASC) VISIBLE,
  INDEX `fk_Produit_has_Couleur_Taille1_idx` (`Taille_idTaille` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_has_Couleur_Produit1`
    FOREIGN KEY (`Produit_idProduit`)
    REFERENCES `mydb`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_has_Couleur_Couleur1`
    FOREIGN KEY (`Couleur_idCouleur`)
    REFERENCES `mydb`.`Couleur` (`idCouleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_has_Couleur_Taille1`
    FOREIGN KEY (`Taille_idTaille`)
    REFERENCES `mydb`.`Taille` (`idTaille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Composer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Composer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Composer` (
  `Commande_idCommande` INT NOT NULL,
  `Quantité` VARCHAR(45) NULL,
  `Produit_has_Couleur_Produit_idProduit` INT NOT NULL,
  `Produit_has_Couleur_Couleur_idCouleur` INT NOT NULL,
  `Produit_has_Couleur_Taille_idTaille` INT NOT NULL,
  PRIMARY KEY (`Commande_idCommande`, `Produit_has_Couleur_Produit_idProduit`, `Produit_has_Couleur_Couleur_idCouleur`, `Produit_has_Couleur_Taille_idTaille`),
  INDEX `fk_Produit_has_Commande_Commande1_idx` (`Commande_idCommande` ASC) VISIBLE,
  INDEX `fk_Composer_Produit_has_Couleur1_idx` (`Produit_has_Couleur_Produit_idProduit` ASC, `Produit_has_Couleur_Couleur_idCouleur` ASC, `Produit_has_Couleur_Taille_idTaille` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_has_Commande_Commande1`
    FOREIGN KEY (`Commande_idCommande`)
    REFERENCES `mydb`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Composer_Produit_has_Couleur1`
    FOREIGN KEY (`Produit_has_Couleur_Produit_idProduit` , `Produit_has_Couleur_Couleur_idCouleur` , `Produit_has_Couleur_Taille_idTaille`)
    REFERENCES `mydb`.`VariantArticle` (`Produit_idProduit` , `Couleur_idCouleur` , `Taille_idTaille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Panier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Panier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Panier` (
  `Client_username` VARCHAR(16) NOT NULL,
  `quantite` VARCHAR(45) NULL,
  `ProduitTailleCouleur_Produit_idProduit` INT NOT NULL,
  `ProduitTailleCouleur_Couleur_idCouleur` INT NOT NULL,
  `ProduitTailleCouleur_Taille_idTaille` INT NOT NULL,
  PRIMARY KEY (`Client_username`, `ProduitTailleCouleur_Produit_idProduit`, `ProduitTailleCouleur_Couleur_idCouleur`, `ProduitTailleCouleur_Taille_idTaille`),
  INDEX `fk_Produit_has_Client_Client1_idx` (`Client_username` ASC) VISIBLE,
  INDEX `fk_Panier_ProduitTailleCouleur1_idx` (`ProduitTailleCouleur_Produit_idProduit` ASC, `ProduitTailleCouleur_Couleur_idCouleur` ASC, `ProduitTailleCouleur_Taille_idTaille` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_has_Client_Client1`
    FOREIGN KEY (`Client_username`)
    REFERENCES `mydb`.`Client` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Panier_ProduitTailleCouleur1`
    FOREIGN KEY (`ProduitTailleCouleur_Produit_idProduit` , `ProduitTailleCouleur_Couleur_idCouleur` , `ProduitTailleCouleur_Taille_idTaille`)
    REFERENCES `mydb`.`VariantArticle` (`Produit_idProduit` , `Couleur_idCouleur` , `Taille_idTaille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Virement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Virement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Virement` (
  `numVirement` INT NOT NULL,
  `Commande_idCommande` INT NOT NULL,
  PRIMARY KEY (`numVirement`),
  INDEX `fk_Virement_Commande1_idx` (`Commande_idCommande` ASC) VISIBLE,
  CONSTRAINT `fk_Virement_Commande1`
    FOREIGN KEY (`Commande_idCommande`)
    REFERENCES `mydb`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paypal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Paypal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Paypal` (
  `numPaiement` INT NOT NULL AUTO_INCREMENT,
  `Commande_idCommande` INT NOT NULL,
  PRIMARY KEY (`numPaiement`),
  INDEX `fk_Paypal_Commande1_idx` (`Commande_idCommande` ASC) VISIBLE,
  CONSTRAINT `fk_Paypal_Commande1`
    FOREIGN KEY (`Commande_idCommande`)
    REFERENCES `mydb`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CarteBancaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CarteBancaire` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CarteBancaire` (
  `idCarteBancaire` INT NOT NULL,
  `numeroBancaire` CHAR(16) NULL,
  `dateExpiration` DATE NULL,
  `cvv` TINYINT(3) NULL,
  `Client_username` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idCarteBancaire`),
  INDEX `fk_CarteBancaire_Client1_idx` (`Client_username` ASC) VISIBLE,
  CONSTRAINT `fk_CarteBancaire_Client1`
    FOREIGN KEY (`Client_username`)
    REFERENCES `mydb`.`Client` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CarteBancaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CarteBancaire` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CarteBancaire` (
  `idCarteBancaire` INT NOT NULL,
  `numeroBancaire` CHAR(16) NULL,
  `dateExpiration` DATE NULL,
  `cvv` TINYINT(3) NULL,
  `Client_username` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idCarteBancaire`),
  INDEX `fk_CarteBancaire_Client1_idx` (`Client_username` ASC) VISIBLE,
  CONSTRAINT `fk_CarteBancaire_Client1`
    FOREIGN KEY (`Client_username`)
    REFERENCES `mydb`.`Client` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
